### ISSUE TITLE
 Fatal error: Uncaught exception 'RuntimeException' with message 'Empty response' 

### ISSUE THREAD

**Issue by fjhadz1** [arodygin/php-linode-api3#2]
->new developer here. 
Not sure, why I'm getting this error:  Fatal error: Uncaught exception 'RuntimeException' with message 'Empty response' 

any ideas?

**Comment by arodygin** [comment]
I have checked the example from the README - it works for me fine.
Could you please provide me with a complete snippet of code to reproduce the problem?

**Comment by fjhadz1** [comment]
Thanks, It seems the problem was the curl SSL certificate. I just added `curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);`  in BaseLinodeApi.php.  and seems working now. I would appreciate if you can also suggest any other method of fixing this.

**Comment by arodygin** [comment]
Since you didn't provide me with any information like your OS, PHP version, and code snippet to reproduce, I can't say for sure what's going on and what is the best way to fix it. But turning the `CURLOPT_SSL_VERIFYPEER` off is definitely a bad idea, as it allows man-in-the-middle attack on https.

Probably this is your case, please check - [https://snippets.webaware.com.au/howto/stop-turning-off-curlopt_ssl_verifypeer-and-fix-your-php-config](https://snippets.webaware.com.au/howto/stop-turning-off-curlopt_ssl_verifypeer-and-fix-your-php-config).

**Comment by fjhadz1** [comment]
Cool, great advice. The link you've given helped me to understand. Yes, I'm using windows 10, Wamp with 5.5.12 php version.

**Comment by arodygin** [comment]
No worries, was happy to help.
